// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  describe("Service db_tree test", function() {
    var MainCtrl, cryptApi, scope, translate;
    beforeEach(module("4treeApp"));
    MainCtrl = void 0;
    scope = void 0;
    cryptApi = void 0;
    translate = void 0;
    beforeEach(inject(function($controller, $rootScope, $translate) {
      var $injector;
      scope = $rootScope.$new();
      MainCtrl = $controller("MainCtrl", {
        $scope: scope
      });
      $injector = angular.injector(["4treeApp"]);
      cryptApi = $injector.get("cryptApi");
      cryptApi.constructor();
      return translate = $translate;
    }));
    return it("Crypt some text", function() {
      var sha, text;
      text = "The Cipher Input 111";
      _.each(cryptApi.methods, function(type, key) {
        var crypted, decrypted;
        crypted = cryptApi.encrypt(text, key);
        decrypted = cryptApi.decrypt(crypted).text;
        console.info(text.length, crypted.length, crypted, cryptApi.decrypt(crypted).err);
        return expect(decrypted).toBe(text);
      });
      console.info('errors = ', cryptApi.decrypt('{"memo":"ФИО","data":"Чувак ты где?","method":"AES","salt":"38777"}'));
      console.info(sha = cryptApi.sha3('sex'));
      expect(sha.length).toBeGreaterThan(5);
    });
  });

}).call(this);
