// Generated by CoffeeScript 1.6.3
(function() {
  "use strict";
  describe("Service calendarBox test", function() {
    var MainCtrl, myService, scope, translate;
    beforeEach(module("4treeApp"));
    MainCtrl = void 0;
    scope = void 0;
    myService = void 0;
    translate = void 0;
    beforeEach(inject(function($controller, $rootScope, $translate) {
      var $injector;
      scope = $rootScope.$new();
      MainCtrl = $controller("MainCtrl", {
        $scope: scope
      });
      $injector = angular.injector(["4treeApp"]);
      myService = $injector.get("calendarBox");
      return translate = $translate;
    }));
    return it("Get 8 mart object fron date", function() {
      var mydate;
      mydate = new Date(2014, 2, 8);
      expect(myService.getDateBox(mydate).day).toEqual('8');
      expect(myService.getDateBox(mydate).month).toEqual('март');
      expect(myService.getDateBox(mydate).week_day).toEqual('сб');
    });
  });

}).call(this);
