// Generated by CoffeeScript 1.6.3
(function() {
  var Tree, async, frommysql, mongoose, removeCollection;

  async = require('async');

  mongoose = require('mongoose');

  require('../../models/_js/model_tree.js');

  Tree = mongoose.model('Tree');

  removeCollection = function(callback) {
    var collection;
    collection = db.collection("trees");
    return collection.remove({}, function(err, count) {
      return callback(err);
    });
  };

  frommysql = function(mysqldate, need_add_hours) {
    var d;
    d = new Date(Date.parse(mysqldate, 'Y-m-d H:i:s'));
    return new Date(d.getTime() - need_add_hours * 60 * 60 * 1000);
  };

  exports.get = function(req, res) {
    var user_id;
    user_id = req.query.user_id;
    console.info("start_import user = ", user_id);
    return async.waterfall([
      removeCollection, function(callback) {
        return pool.query('SELECT * FROM tree_users WHERE id=?', [user_id], function(err, user, fields) {
          console.info('user = ', user);
          return callback(err, user[0]);
        });
      }, function(user, callback) {
        return pool.query('SELECT * FROM tree WHERE user_id=?', [user_id], function(err, rows, fields) {
          console.info('mysql = ', err);
          return callback(err, rows, user);
        });
      }, function(rows, user, callback) {
        var collection, current_timezone_offset, need_add_hours, now;
        collection = db.collection("new_tree");
        now = new Date();
        current_timezone_offset = now.getTimezoneOffset() / 60;
        need_add_hours = current_timezone_offset - user.time_dif;
        console.info('time_zone', user.time_dif, current_timezone_offset, need_add_hours);
        return async.eachLimit(rows, 50, function(row, callback) {
          var new_date, one_note;
          one_note = new Tree;
          one_note['id'] = row.id;
          one_note['title'] = row.title;
          one_note['text'] = row.text;
          one_note['parent_id'] = row.parent_id;
          one_note['parent'] = row.parent_id;
          one_note['pos'] = row.position;
          one_note['user_id'] = row.user_id;
          if (row.node_icon) {
            one_note['icon'] = row.node_icon;
          }
          if (row.del !== 0) {
            one_note['del'] = 1;
          }
          if (row.smth) {
            one_note['old_tag'] = row.smth;
          }
          if (row.adddate !== '0000-00-00 00:00:00') {
            new_date = frommysql(row.adddate, need_add_hours);
            one_note['add_tm'] = new_date;
          }
          if (row.date1 !== '0000-00-00 00:00:00') {
            new_date = frommysql(row.date1, need_add_hours);
            one_note['date1'] = new_date;
          }
          if (row.date2 !== '0000-00-00 00:00:00') {
            new_date = frommysql(row.date2, need_add_hours);
            one_note['date2'] = new_date;
          }
          if (row.did !== '0000-00-00 00:00:00') {
            new_date = frommysql(row.did, need_add_hours);
            one_note['did'] = new_date;
          }
          return one_note.save(function(err, result) {
            console.info('saved', err);
            return callback(err, rows);
          });
        }, function(err) {
          return callback(err);
        });
      }
    ], function(err, rows) {
      return res.send('ok');
    });
  };

}).call(this);
