// Generated by CoffeeScript 1.7.1
(function() {
  "use strict";
  angular.module("ngSocket", []).factory("$socket", [
    "$rootScope", function($rootScope) {
      var addListener, addListenerOnce, angularCallback, emit, is_online, removeAllListeners, removeListener, socket;
      if (typeof socket === "undefined") {
        socket = io.connect();
      }
      angularCallback = function(callback) {
        return function() {
          var args;
          if (callback) {
            args = arguments;
            $rootScope.$apply(function() {
              callback.apply(socket, args);
            });
          }
        };
      };
      addListener = function(name, scope, callback) {
        if (arguments.length === 2) {
          scope = null;
          callback = arguments[1];
        }
        socket.addListener(name, angularCallback(callback));
        if (scope !== null) {
          scope.$on("$destroy", function() {
            removeListener(name, callback);
          });
        }
      };
      addListenerOnce = function(name, callback) {
        socket.once(name, angularCallback(callback));
      };
      removeListener = function(name, callback) {
        socket.removeListener(name, angularCallback(callback));
      };
      removeAllListeners = function(name) {
        socket.removeAllListeners(name);
      };
      emit = function(name, data, callback) {
        socket.emit(name, data, angularCallback(callback));
      };
      is_online = function() {
        return socket.socket.connected;
      };
      return {
        is_online: is_online,
        addListener: addListener,
        on: addListener,
        once: addListenerOnce,
        removeListener: removeListener,
        removeAllListeners: removeAllListeners,
        emit: emit
      };
    }
  ]);

}).call(this);

//# sourceMappingURL=ngSocket.map
