// Generated by CoffeeScript 1.6.2
(function() {
  "use strict";  describe("Controller: MainCtrl", function() {
    var MainCtrl, scope;

    beforeEach(module("4treeApp"));
    MainCtrl = void 0;
    scope = void 0;
    beforeEach(inject(function($controller, $rootScope) {
      scope = $rootScope.$new();
      return MainCtrl = $controller("MainCtrl", {
        $scope: scope
      });
    }));
    return it("should attach a list of awesomeThings to the scope", function() {
      return expect(scope.awesomeThings.length).toBe(8);
    });
  });

}).call(this);
