// Generated by CoffeeScript 1.6.3
(function() {
  var CryptoJS;

  CryptoJS = require("crypto-js");

  exports.JSON_stringify = function(json) {
    var delete_, string, _id, _sha1;
    delete_ = function(key, value) {
      if (key[0] === '_') {
        return void 0;
      } else {
        return value;
      }
    };
    string = JSON.stringify(json, delete_, 0);
    _id = json != null ? json._id : void 0;
    _sha1 = CryptoJS.SHA1(JSON.stringify(string)).toString().substr(0, 7);
    return {
      _id: _id,
      _sha1: _sha1,
      string: string
    };
  };

}).call(this);
