// Generated by CoffeeScript 1.7.1
(function() {
  var customLevels, level, mylog, mynewlog, safeJsonStringify, winston, _;

  winston = require('winston');

  _ = require('underscore');

  require('winston-logstash');

  safeJsonStringify = function(o) {
    var cache;
    cache = [];
    return JSON.stringify(o, function(key, value) {
      if (typeof value === "object" && value !== null) {
        if (cache.indexOf(value) !== -1) {
          return;
        }
        cache.push(value);
      }
      return value;
    });
  };


  /* Сервер для ведения логов
  bin/logstash -e 'input { tcp { port => 28777 type=>"sample" } } output { elasticsearch { host => localhost } } filter { json { source => "message"} }'
   */

  winston.add(winston.transports.Logstash, {
    port: 28777,
    node_name: '4TREE',
    host: '127.0.0.1'
  });

  customLevels = {
    transports: [],
    levels: {
      sync: 1,
      info: 2,
      debug: 3,
      trace: 4,
      error: 5
    },
    colors: {
      sync: 'green',
      info: 'yellow',
      debug: 'blue',
      trace: 'magenta',
      error: 'red'
    }
  };

  level = 'error';

  customLevels.transports.push(new winston.transports.Logstash({
    port: 28777,
    node_name: 'my node name',
    host: '127.0.0.1',
    level: level
  }));

  customLevels.transports.push(new winston.transports.Console({
    level: level,
    colorize: 'true'
  }));

  customLevels.transports.push(new winston.transports.File({
    filename: 'mylog.log',
    level: level
  }));

  winston.addColors(customLevels.colors);

  mylog = new winston.Logger(customLevels);

  mynewlog = (function() {
    var cached_mylog;
    cached_mylog = mylog.log;
    return function() {
      if (arguments[2]) {
        arguments[2] = JSON.parse(safeJsonStringify(arguments[2]));
      }
      return cached_mylog.apply(this, arguments);
    };
  })();

  mylog = new winston.Logger(customLevels);

  mylog.log = mynewlog;

  mylog.info = mynewlog;

  exports.mylog = mylog;

}).call(this);

//# sourceMappingURL=mylog.map
