// Generated by CoffeeScript 1.6.3
/*
  Класс для работы с текстами основан на diff
*/


(function() {
  var TextController;

  TextController = (function() {
    TextController.$inject = ['$timeout', '$scope', '$q'];

    function TextController(timeout, scope, q) {
      var mythis;
      this.timeout = timeout;
      this.scope = scope;
      this.q = q;
      mythis = this;
      _.each(this.textToLoad, function(txt) {
        var key;
        key = mythis.sha(txt);
        console.info('sha of txt = ', key);
        return mythis.textDB[key] = txt;
      });
      this.scope.txt = 'Пусто';
      this.scope.$watch('tree', function(old_val, new_val) {
        var _ref;
        if (old_val !== new_val) {
          console.info('watch', new_val);
          if ((_ref = mythis.scope.tree) != null ? _ref.text_id : void 0) {
            return mythis.getTextByShaId(mythis.scope.tree.text_id).then(function(txt) {
              return mythis.scope.txt = txt;
            });
          }
        }
      });
      console.info('DB = ', this.textDB);
    }

    TextController.prototype.textToLoad = {
      '': 'Мама мыла раму'
    };

    TextController.prototype.textDB = {};

    TextController.prototype.getTextByShaId = function(sha_id) {
      var dfd, mythis;
      console.info("!!!", this.q);
      dfd = this.q.defer();
      mythis = this;
      if (this.textDB) {
        this.timeout(function() {
          return dfd.resolve(mythis.textDB[sha_id]);
        }, 3000);
      } else {
        dfd.resolve();
      }
      return dfd.promise;
    };

    TextController.prototype.sha = function(txt) {
      return CryptoJS.SHA3(txt, {
        outputLength: 256
      }).toString();
    };

    return TextController;

  })();

  angular.module("4treeApp").controller('textController', TextController);

}).call(this);
