// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("4treeApp").directive("myDraggable", function() {
    return {
      link: function(scope, el, attrs) {
        el.draggable({
          connectToSortable: attrs.myDraggable,
          helper: "clone",
          appendTo: "#w_main",
          distance: 10,
          stop: function(event, ui) {
            return console.info('draggable stop', ui);
          }
        });
        el.disableSelection();
      }
    };
  });

  angular.module("4treeApp").directive("myTree8", function() {
    return {
      restrict: "A",
      scope: {
        tree: '=',
        fn: '=',
        set: '=',
        db: '=',
        panel_id: '=panelid'
      },
      replace: true,
      transclude: false,
      templateUrl: "views/subviews/view_one_line0.html",
      link: function($scope, $element, $attributes) {}
    };
  });

  angular.module("4treeApp").directive("member", function($compile, $rootScope, $timeout) {
    return {
      restrict: 'E',
      replace: true,
      transclude: false,
      scope: {
        tree: '=member',
        fn: '=',
        db: '=',
        set: '=',
        panel_id: '=panelid'
      },
      templateUrl: 'views/subviews/view_one_line_10.html',
      template2: "<div style='font-size:10px'>" + "<div contenteditable='true' ng-model='tree.title'></div>" + "</div>",
      link: function(scope, element, attrs) {
        console.time('treeRenderTime');
        $timeout(function() {
          return console.timeEnd('treeRenderTime');
        });
        if (scope.tree._childs > 0 && scope.tree.panel[1]._open) {
          element.append('<my-tree-childs tree="fn.service.db_tree.jsFindByParent(tree._id)" fn="fn" set="set" db="db" panelid="panel_id"></my-tree-childs>');
          return $compile(element.contents())(scope);
        }
      }
    };
  });

  angular.module("4treeApp").directive("myTreeChilds", function($compile) {
    return {
      restrict: "E",
      scope: {
        tree: '=',
        fn: '=',
        db: '=',
        set: '=',
        panel_id: '=panelid'
      },
      replace: true,
      transclude: false,
      template: "<ul><member member='note' fn='fn' set='set' db='db' panelid='panel_id' bindonce ng-repeat='note in tree'></member></ul>",
      link: function($scope, $element, $attributes) {}
    };
  });

  angular.module("4treeApp").directive("mySortable", function() {
    return {
      require: "?ngModel",
      link: function(scope, el, attrs) {
        el.sortable({
          revert: false,
          distance: 10
        });
        el.disableSelection();
        el.on("sortstart", function(event, ui) {
          console.info('start', ui.item[0].dataset.id);
          $(this).data().sort_id = ui.item[0].dataset.id;
          return $(".tree_tmpl[data-id='" + $(this).data().sort_id + "']").addClass('drag_now');
        });
        el.on("sortbeforestop", function(event, ui) {
          var from, from_data_id, to, to_data_parent_id;
          event.stopPropagation();
          event.preventDefault();
          from_data_id = $(this).data().sort_id;
          $(".tree_tmpl[data-id='" + $(this).data().sort_id + "']").removeClass('drag_now');
          from = angular.element(ui.item).scope().$index;
          to = el.children().index(ui.item);
          to = angular.element(event.target).children("[data-id='" + from_data_id + "']").index();
          to_data_parent_id = angular.element(this).attr('data-parent-id');
          console.info("FROM", from_data_id, "TO", to_data_parent_id);
          if (to >= 0) {
            scope.$apply(function() {
              if (from >= 0 || true) {
                console.info('sorted', {
                  to: to,
                  from: from
                }, angular.element(ui.item).scope().tree);
                scope.$emit("my-sorted", {
                  from: from,
                  to: to,
                  from_id: from_data_id,
                  to_id: to_data_parent_id
                });
              } else {
                console.info('created', {
                  to: to
                });
                scope.$emit("my-created", {
                  to_id: to_data_parent_id,
                  to_index: to,
                  name: ui.item.text()
                });
                ui.item.remove();
              }
            });
          }
        });
      }
    };
  });

}).call(this);
