// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("4treeApp").directive("jqShowEffect", [
    "$timeout", function($timeout) {
      return {
        restrict: "A",
        link: function($scope, element, attrs) {
          var callback, delay, duration, hideImmediately, jqElm, options, passedOptions, type;
          passedOptions = $scope.$eval(attrs.jqOptions);
          options = {
            type: "fade",
            duration: 200,
            delay: 0,
            hideImmediately: false,
            callback: null
          };
          $.extend(options, passedOptions);
          type = options.type;
          duration = options.duration;
          callback = options.callback;
          delay = options.delay;
          hideImmediately = options.hideImmediately;
          jqElm = $(element);
          $scope.$watch(attrs.jqShowEffect, function(value) {
            if (hideImmediately && !value) {
              jqElm.hide(0, callback);
            } else {
              $timeout((function() {
                if (type === "fade") {
                  if (value) {
                    jqElm.fadeIn(duration, callback);
                  } else {
                    jqElm.fadeOut(duration, callback);
                  }
                } else if (type === "slide") {
                  if (value) {
                    jqElm.slideDown(duration, callback);
                  } else {
                    jqElm.slideUp(duration, callback);
                  }
                } else {
                  if (value) {
                    jqElm.show(duration, callback);
                  } else {
                    jqElm.hide(duration, callback);
                  }
                }
              }), delay);
            }
          });
        }
      };
    }
  ]);

}).call(this);
