// Generated by CoffeeScript 1.6.3
(function() {
  var suspend_timer_off, suspend_timer_on;

  suspend_timer_off = _.debounce(function() {
    return false;
  }, 3);

  suspend_timer_on = _.debounce(function() {
    return false;
  }, 120);

  angular.module("4treeApp").directive("plumbConnect", function($timeout) {
    return {
      replace: true,
      require: "?ngModel",
      link: function(scope, element, attrs, ngModel) {
        var parent_element;
        parent_element = $(element).parents("li:first").parents("li:first").find('.col3');
        suspend_timer_off();
        jsPlumb.Defaults.Container = $(".mindmap .content");
        jsPlumb.Defaults.DragOptions = {
          cursor: 'pointer',
          zIndex: 2000
        };
        jsPlumb.Defaults.PaintStyle = {
          lineWidth: 1,
          strokeStyle: "#888"
        };
        jsPlumb.Defaults.Connector = [
          "Bezier", {
            curviness: 30
          }
        ];
        jsPlumb.Defaults.Endpoint = [
          "Blank", {
            radius: 5
          }
        ];
        jsPlumb.Defaults.EndpointStyle = {
          fillStyle: "#567567"
        };
        if (parent_element.length && true) {
          $timeout(function() {
            jsPlumb.Defaults.Container = parent_element.parents("li:first");
            jsPlumb.connect({
              source: parent_element,
              target: element,
              paintStyle: {
                lineWidth: 1,
                strokeStyle: "#888"
              },
              anchors: [[1, 1, 1, 0, -1, -1], [0, 1, -1, 0, 1, -1]]
            });
            return suspend_timer_on();
          }, 5);
        }
        element.on('$destroy', function() {
          console.info('destroy ' + attrs.id);
          suspend_timer_off();
          jsPlumb.detachAllConnections(element);
          return suspend_timer_on();
        });
      }
    };
  });

  if (false) {
    jsPlumb.makeTarget(element, {
      anchor: "Continuous",
      maxConnections: 2
    });
    jsPlumb.draggable(element, {
      containment: "parent"
    });
    element.bind("dblclick", function(e) {
      jsPlumb.detachAllConnections($(this));
      $(this).remove();
      e.stopPropagation();
      scope.$parent.removeState(attrs.identifier);
      scope.$parent.$digest();
    });
  }

}).call(this);
