// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("4treeApp").directive("contenteditable", function() {
    return {
      restrict: "A",
      require: "?ngModel",
      link: function(scope, element, attrs, ngModel) {
        var readViewText;
        readViewText = function() {
          var html;
          html = element.html();
          if (attrs.stripBr && html === "<br>") {
            html = "";
          }
          return ngModel.$setViewValue(html);
        };
        if (!ngModel) {
          return;
        }
        ngModel.$render = function() {
          return element.html(ngModel.$viewValue || "");
        };
        return element.on("blur keyup change", function() {
          return scope.$apply(readViewText);
        });
      }
    };
  });

}).call(this);
