// Generated by CoffeeScript 1.6.3
(function() {
  var $, Imap, MongoClient, OAuthUsersModel, Pool, RedisStore, Tree, allWorkers, app, async, cluster, db, express, fs, http, i, imap, io, mail_service, md5, model, mongoose, mysql, notifier, notifier_instance, numCPUs, oauthserver, publisher, redis, redis_client, server, subscriber, test_tmp, uristring, worker, workers, _, _i;

  cluster = require('cluster');

  http = require('http');

  numCPUs = require('os').cpus().length;

  $ = require('jquery');

  if (cluster.isMaster) {
    server = require('http').createServer();
    io = require('socket.io').listen(server);
    RedisStore = require('socket.io/lib/stores/redis');
    redis = require('socket.io/node_modules/redis');
    publisher = redis.createClient;
    subscriber = redis.createClient;
    io = require('socket.io').listen(server, {
      log: false
    });
    io.set('store', new RedisStore({
      redisPub: redis.createClient(),
      redisSub: redis.createClient(),
      redisClient: redis.createClient()
    }));
    workers = {};
    allWorkers = {};
    numCPUs = 0;
    for (i = _i = 0; 0 <= numCPUs ? _i <= numCPUs : _i >= numCPUs; i = 0 <= numCPUs ? ++_i : --_i) {
      worker = cluster.fork();
      allWorkers[worker.process.pid] = worker;
    }
    cluster.on('exit', function(worker, code, signal) {
      console.log('worker ' + worker.process.pid + ' died');
      worker = cluster.fork();
      delete workerAll[worker.process.pid];
      return workerAll[worker.process.pid] = worker;
    });
    cluster.on('fork', function(worker, address) {
      return console.info("FORK: ", worker.id);
    });
  } else {
    express = require("express");
    app = express();
    server = require("http").createServer(app);
    RedisStore = require("socket.io/lib/stores/redis");
    redis = require("socket.io/node_modules/redis");
    _ = require('underscore');
    mysql = require('mysql');
    md5 = require('MD5');
    Pool = require('mysql-simple-pool');
    async = require('async');
    fs = require('fs');
    MongoClient = require('mongodb').MongoClient;
    Imap = require('imap');
    notifier = require('mail-notifier');
    imap = {
      username: "4tree@4tree.ru",
      user: "4tree@4tree.ru",
      password: "uuS4foos_VE",
      host: "mail.4tree.ru",
      port: 993,
      secure: true,
      tls: true,
      debug: function(msg) {
        return console.info("MAIL: ", msg);
      }
    };
    notifier_instance = notifier(imap).on('mail', function(mail) {
      return mail_service.save_mail_to_tree(mail);
    });
    notifier_instance.start();
    /*
    process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
    
    imap_connection = new Imap(imap);
    
    
    openInbox = (cb)->
      imap.openBox('INBOX', false, cb);
    
    imap_connection.once 'ready', ()->
      console.info 'Mail Ready!!!!!!!!!!!!!!!!!'
    
    imap_connection.on 'error', (err)->
      console.info 'Mail error', err
    
    imap_connection.connect();
    */

    mongoose = require("mongoose");
    mongoose.set("debug", true);
    uristring = "mongodb://127.0.0.1:27017/4tree";
    mongoose.connect(uristring, function(err, res) {
      if (err) {
        return console.log("ERROR connecting to: " + uristring + ". " + err);
      }
    });
    mongoose.connection.on('connected', function() {
      return console.log('Mongoose default connection open to ' + uristring);
    });
    mongoose.connection.on('error', function(err) {
      return console.log('Mongoose Error: ' + err);
    });
    mongoose.connection.on('disconnected', function() {
      return console.log('Mongoose Disconnected');
    });
    require('../models/_js/model_tree.js');
    Tree = mongoose.model('Tree');
    test_tmp = function() {
      var query, t, tm;
      require('../models/_js/model_tree.js');
      Tree = mongoose.model('Tree');
      if (true) {
        t = Tree.create({
          Country: "England",
          GroupName: "D",
          CreatedOn: Date.now(),
          Tags: {
            title: "Hi!!!"
          }
        });
      }
      query = {
        Country: "England"
      };
      tm = new Date().getTime();
      return Tree.find({}, function(err, docs) {
        return async.eachLimit(docs, 50, function(doc, callback) {
          doc.GroupName = "MY COUNTRY-999" + new Date().getTime();
          return doc.save(callback);
        }, function() {
          return console.info("SPEED", new Date().getTime() - tm);
        });
      });
    };
    oauthserver = require("node-oauth2-server");
    model = require("node-oauth2-server/examples/mongodb/model.js");
    app.configure(function() {
      app.oauth = oauthserver({
        model: model,
        grants: ["password", "refresh_token"],
        debug: false
      });
      app.use(express.bodyParser());
    });
    app.all("/oauth/token", app.oauth.grant());
    app.use(app.oauth.errorHandler());
    /*app.get "/", app.oauth.authorise(), (req, res) ->
      res.send "Secret area"
      return
    */

    app.use(app.oauth.errorHandler());
    OAuthUsersModel = mongoose.model('OAuthUsers');
    mail_service = {
      save_mail_to_tree: function(mail) {
        this.getUserId(mail).then(function(result) {
          return console.info("FOUND CLIENTS = ", result);
        });
        if (mail.attachments) {
          return async.each(mail.attachments, function(file, callback) {
            console.info("save_file", file);
            return fs.writeFile("user_data/" + file.contentId + file.fileName, file.content, function(err) {
              console.info("error", err);
              return callback(err);
            });
          });
        }
      },
      getUserId: function(mail) {
        var check_emails, dfd, found_clients, mymails, mythis;
        mythis = this;
        dfd = $.Deferred();
        check_emails = [];
        if (mail['to']) {
          mymails = mail['from'].concat(mail['to']);
        }
        if (mail['cc']) {
          mymails = mymails.concat(mail['cc']);
        }
        _.each(mymails, function(from) {
          console.info("ADRESS", from);
          return check_emails.push(from.address);
        });
        check_emails = _.uniq(check_emails, function(item) {
          return item;
        });
        found_clients = [];
        async.each(check_emails, function(item, callback) {
          return mythis.findUserByEmail(item).then(function(result) {
            if (result) {
              found_clients = found_clients.concat(result);
            }
            return callback();
          });
        }, function() {
          return dfd.resolve(found_clients);
        });
        return dfd.promise();
      },
      findUserByEmail: function(email) {
        var dfd;
        dfd = $.Deferred();
        OAuthUsersModel.find({
          email: email
        }, function(err, result) {
          return dfd.resolve(result);
        });
        return dfd.promise();
      }
    };
    db = void 0;
    MongoClient.connect("mongodb://127.0.0.1:27017/4tree", function(err, mydb) {
      db = mydb;
      return global.db = db;
    });
    global.pool = new Pool(100, {
      host: '127.0.0.1',
      user: 'root',
      password: 'See6thoh',
      database: 'h116'
    });
    redis_client = redis.createClient();
    subscriber = redis.createClient();
    publisher = redis.createClient();
    subscriber.on("error", function(e) {
      return console.log("subscriber", e.stack);
    });
    publisher.on("error", function(e) {
      return console.log("publisher", e.stack);
    });
    io = require('socket.io').listen(server, {
      log: false
    });
    io.set('store', new RedisStore({
      redisPub: redis.createClient(),
      redisSub: redis.createClient(),
      redisClient: redis.createClient()
    }));
    app.configure(function() {
      var server_is;
      app.use(express.compress());
      server_is = "app";
      app.use(express["static"](__dirname + "/../../" + server_is + "/images", {
        maxAge: 86400000
      }));
      app.use(express["static"](__dirname + "/../../" + server_is + "/images/do_type", {
        maxAge: 86400000
      }));
      return app.use(express["static"](__dirname + "/../../" + server_is));
    });
    subscriber.subscribe('chanel_2');
    subscriber.subscribe('chanel_1');
    subscriber.on("message", function(chanel, message) {
      try {
        message = JSON.parse(message);
      } catch (_error) {

      }
      return console.info(chanel, message[0], message[1]);
    });
    exports.newMessage = function(request, response) {
      var collection;
      console.info('hi!');
      publisher.publish('chanel_1', JSON.stringify(['user_connected', 'John Wezel']));
      response.send('HELLO', 'IM BODY!!!');
      collection = db.collection("tree");
      return collection.update({
        id: 146
      }, {
        $push: {
          tags: {
            enter_time: new Date()
          }
        }
      }, {
        multi: false,
        upsert: true
      }, function(err, result) {
        return console.info(result, err);
      });
    };
    exports.sync = function(req, res) {
      var notes, token;
      token = req.query.token;
      notes = req.body.sync_data_to_send.notes;
      return async.eachLimit(notes, 50, function(note, callback) {
        var _id;
        _id = note._id;
        delete note._id;
        return Tree.update({
          _id: _id
        }, note, function(err) {
          if (err) {
            console.info(err);
          }
          return callback(err);
        });
      }, function(callback) {
        return res.send(true);
      });
    };
    app.post('/api/v1/sync', app.oauth.authorise(), exports.sync);
    app.get('/api/v1/message', exports.newMessage);
    app.get('/api/import_from_mysql', function(req, res) {
      return (require('../get/_js/server_import_from_mysql')).get(req, res);
    });
    app.get('/api/v2/tree', app.oauth.authorise(), function(req, res) {
      return (require('../get/_js/server_get_all_tree')).get(req, res);
    });
    app.get('/api/v2/fake_names', function(req, res) {
      return (require('../get/_js/server_fake_fpk_names')).get(req, res);
    });
    server.listen(8888);
  }

}).call(this);
