// Generated by CoffeeScript 1.6.3
(function() {
  var diff_time, send_to_server, server_tree1, server_tree2, sync, time1, time2;

  time1 = new Date();

  time2 = new Date(2011, 1, 1);

  send_to_server = {
    'current_time': time1,
    'last_sync_time': time2,
    'sync_journal': sync_journal,
    'sync_data': sync_data
  };

  server_tree1 = [
    {
      id: 8,
      title: 'hello',
      _title: new Date(),
      note: 'Thanks',
      _note: new Date()
    }
  ];

  server_tree2 = [
    {
      id: 8,
      title: {
        val: 'hello',
        tm: new Date()
      },
      note: {
        val: 'hello',
        tm: new Date()
      },
      tags: {
        val: ['срочно', 'завтра'],
        tm: new Date()
      },
      _change_time: new Date()
    }
  ];

  diff_time = sync.calcDiffTime(send_to_server.current_time);

  sync = {
    calcDiffTime: function(current_time) {
      return current_time.getTime() - new Date().getTime();
    }
  };

}).call(this);
