// Generated by CoffeeScript 1.6.3
(function() {
  var change_journal, send_to_client, send_to_server, tree_note;

  send_to_server = {
    'current_time': time1,
    'last_sync_time': time2,
    'sync_data': sync_data,
    'confirm_delete': confirm_delete
  };

  send_to_client = {
    'new_id_collision': [
      {
        old_id: -111,
        new_id: 567
      }, {
        old_id: -211,
        new_id: 897
      }
    ],
    'id_synced': [456, 432, 243, 2444],
    'id_need_delete': [654, 323, 234, 342],
    'sync_data_from_server': sync_data
  };

  tree_note = {
    id: 1,
    user: {
      id: 11,
      name: 'John Wezel'
    },
    share: [
      {
        id: 12,
        rights: {
          write: true,
          read: true
        }
      }, {
        id: 18,
        rights: {
          write: false,
          read: true
        }
      }
    ],
    title: 'Привет',
    tags: ['работа', 'срочно', 'на сайт'],
    comments: [
      {
        id: 1,
        title: 'Классная статья!'
      }, {
        id: 2,
        title: 'Мне тоже нравится'
      }, {
        id: 3,
        title: 'Отлично написано'
      }, {
        id: 4,
        title: 'Можно запомнить'
      }
    ],
    likes: [
      {
        user_id: 11,
        name: 'Валентина',
        avatar: 'img/12.png'
      }
    ],
    options: [
      {
        store_to_web: {
          turn_on: true,
          link: 's8xd'
        }
      }, {
        like: true
      }, {
        favorit_panel: 'right'
      }
    ]
  };

  change_journal = [
    {
      id: 1,
      changes: {
        'user.id': 1392720725000,
        'title': 1392720725000,
        'comments.1': 1392720725000,
        'options.store_to_web.turn_on': 1392720725010
      },
      change_time: 1392720725000
    }
  ];

}).call(this);
