// Generated by CoffeeScript 1.6.3
(function() {
  angular.module("4treeApp").service('calendarBox', [
    '$translate', function($translate) {
      return {
        constructor: function($timeout) {
          this.$timeout = $timeout;
          return this.color = 'grey';
        },
        getDate: function(args) {
          return 1;
        },
        getDates: function(args) {
          return this.getDate(args.today);
        },
        getDateBox: function(date) {
          var add, answer, day, month, month1, myclass, week_day;
          if (!this.current_month) {
            this.current_month = (new Date()).getMonth();
          }
          day = date.getDate().toString();
          month1 = date.getMonth();
          week_day = $translate('WEEKDAY.' + (date.getDay()));
          month = $translate('MONTH.' + (month1 + 1));
          myclass = 'week_' + (date.getDay());
          if (date.toString() === new Date().toString()) {
            myclass = "today";
          }
          if (this.current_month % 2) {
            add = 1;
          }
          if ((month1 + add) % 2) {
            myclass += " odd_month";
          }
          if (month1 === this.current_month) {
            myclass += " this_month";
          }
          return answer = {
            day: day,
            month: month,
            week_day: week_day,
            myclass: myclass
          };
        }
      };
    }
  ]);

}).call(this);
