// Generated by CoffeeScript 1.6.3
(function() {
  var d, sync, _g, _sync_g;

  _g = 1;

  _sync_g = 8;

  d = {
    _id: ObjectId('4445445446'),
    title: 'Привет',
    parent: 8,
    tags: [
      {
        _id: ObjectId('4445445446'),
        title: 'Новости'
      }, {
        _id: ObjectId('4445445448'),
        title: 'АСЭТД'
      }
    ],
    comments: [
      {
        _id: ObjectId('4445445449'),
        text: "Hello frend!"
      }, {
        _id: ObjectId('4445445410'),
        text: "Hi!"
      }
    ],
    sync: {
      '_last': {
        _g: 1,
        tm: 2233244
      },
      'title': {
        _g: 1,
        tm: 2233244
      },
      'parent': {
        _g: 5,
        tm: 4546464
      },
      'tags': {
        _g: 2,
        tm: 5844644
      },
      'comments.4445445449.text': {
        _g: 3,
        tm: 4797797
      },
      'comments.4445445410.text': {
        _g: 4,
        tm: 7788877
      }
    }
  };

  sync = {
    insert_gen: 1,
    update_gen: 1,
    delete_gen: 1,
    tm: 4323,
    server_tm: 5547
  };

}).call(this);
