// Generated by CoffeeScript 1.6.2
(function() {
  var By, ptor;

  By = protractor.By;

  ptor = protractor.getInstance();

  describe("angularjs homepage!!!", function() {
    return it("should greet the named user", function() {
      var greeting;

      browser.get("http://localhost:8888/");
      element(By.model("myname")).clear();
      element(By.model("myname")).sendKeys("Julie");
      greeting = element(By.binding("myname"));
      return expect(greeting.getText()).toEqual("Julie");
    });
  });

  describe("A suite", function() {
    return it("contains spec with an expectation", function() {
      var greeting;

      browser.get("http://localhost:8888/");
      element(By.model("myname")).clear();
      element(By.model("myname")).sendKeys("John");
      greeting = element(By.binding("myname"));
      return expect(greeting.getText()).toEqual("John");
    });
  });

}).call(this);
