// Generated by CoffeeScript 1.6.3
(function() {
  var http, webapp;

  webapp = require('server');

  http = require('http');

  describe('First Test', function() {
    return it('test №1', function() {
      var options, request;
      options = {
        host: 'ya.ru',
        port: 80,
        path: '/'
      };
      request = http.get(options, function(response) {
        return response.on('data', function(chunk) {
          console.log('body: ' + chunk);
          return asyncSpecDone();
        });
      });
      expect(true).toEqual(true);
      asyncSpecWait();
      return request.on('error', function(error) {});
    });
  });

  /*	it "shows asynchronous test", ->
  	  setTimeout (->
  	    expect("second").toEqual "second"
  	    asyncSpecDone()
  	    return
  	  ), 100
  	  expect("first").toEqual "first"
  	  asyncSpecWait()
  	  return
  */


}).call(this);
