// Generated by CoffeeScript 1.6.2
(function() {
  angular.module("4treeApp", ["ngCookies", "ngResource", "ngSanitize", "ngRoute", "pasvaz.bindonce", "pascalprecht.translate", "ngTouch", "sun.scrollable"]);

  angular.module("4treeApp").config([
    "$translateProvider", "$routeProvider", function($translateProvider, $routeProvider) {
      $routeProvider.when("/", {
        templateUrl: "views/main.html",
        controller: "MainCtrl"
      }).otherwise({
        redirectTo: "/"
      });
      $translateProvider.translations("en", {
        TITLE: "Hello",
        FOO: "This is a paragraph"
      });
      $translateProvider.translations("de", {
        TITLE: "Hallo",
        FOO: "Dies ist ein Paragraph"
      });
      return $translateProvider.preferredLanguage("en");
    }
  ]);

  angular.module("4treeApp").directive("scrollpane", function($compile) {
    return {
      restrict: "A",
      link: function(scope, element, attrs) {
        var api;

        console.info(element);
        element.addClass("scroll-pane");
        element.jScrollPane();
        api = element.data("jsp");
        return scope.$watch((function() {
          return element.find("." + attrs.scrollpane).length;
        }), function(length) {
          api.reinitialise();
        });
      }
    };
  });

}).call(this);
